# Replace the "❯" symbol in the prompt with "➜"
[character]
# success_symbol = "[➜](green)"

[aws]
disabled = true

[ruby]
format = ' [ruby:\($version\)]($style)'
# style = 'red'

[nodejs]
disabled = true
format = '[node:\($version\)]($style)'
style = 'green'

[package]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = ''
style = 'blue'

[git_status]
style = 'red'

[time]
disabled = true

[cmd_duration]
disabled = true
