command_timeout = 1000

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$line_break\
$character"""
# Replace the "❯" symbol in the prompt with "➜"
[character]
# success_symbol = "[➜](green)"

[aws]
disabled = true

[ruby]
format = ' [ruby:\($version\)]($style)'
# style = 'red'

[nodejs]
disabled = true
format = '[node:\($version\)]($style)'
style = 'green'

[package]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = ''
style = 'blue'

[git_status]
style = 'red'

[time]
disabled = false
format = ' [\[$time\]]($style) '

[cmd_duration]
disabled = true

[docker_context]
disabled = true
